/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as CommunityImpactRouteImport } from './routes/community-impact'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CounselingRouteImport } from './routes/counseling'
import { Route as DotSapRouteImport } from './routes/dot-sap'
import { Route as DrugTestingRouteImport } from './routes/drug-testing'
import { Route as DuiRouteImport } from './routes/dui'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityImpactRoute = CommunityImpactRouteImport.update({
  id: '/community-impact',
  path: '/community-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselingRoute = CounselingRouteImport.update({
  id: '/counseling',
  path: '/counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const DotSapRoute = DotSapRouteImport.update({
  id: '/dot-sap',
  path: '/dot-sap',
  getParentRoute: () => rootRouteImport,
} as any)
const DrugTestingRoute = DrugTestingRouteImport.update({
  id: '/drug-testing',
  path: '/drug-testing',
  getParentRoute: () => rootRouteImport,
} as any)
const DuiRoute = DuiRouteImport.update({
  id: '/dui',
  path: '/dui',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/classes': typeof ClassesRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/counseling': typeof CounselingRoute
  '/dot-sap': typeof DotSapRoute
  '/drug-testing': typeof DrugTestingRoute
  '/dui': typeof DuiRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/classes': typeof ClassesRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/counseling': typeof CounselingRoute
  '/dot-sap': typeof DotSapRoute
  '/drug-testing': typeof DrugTestingRoute
  '/dui': typeof DuiRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/classes': typeof ClassesRoute
  '/community-impact': typeof CommunityImpactRoute
  '/contact': typeof ContactRoute
  '/counseling': typeof CounselingRoute
  '/dot-sap': typeof DotSapRoute
  '/drug-testing': typeof DrugTestingRoute
  '/dui': typeof DuiRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/classes'
    | '/community-impact'
    | '/contact'
    | '/counseling'
    | '/dot-sap'
    | '/drug-testing'
    | '/dui'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/classes'
    | '/community-impact'
    | '/contact'
    | '/counseling'
    | '/dot-sap'
    | '/drug-testing'
    | '/dui'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/classes'
    | '/community-impact'
    | '/contact'
    | '/counseling'
    | '/dot-sap'
    | '/drug-testing'
    | '/dui'
    | '/faq'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ClassesRoute: typeof ClassesRoute
  CommunityImpactRoute: typeof CommunityImpactRoute
  ContactRoute: typeof ContactRoute
  CounselingRoute: typeof CounselingRoute
  DotSapRoute: typeof DotSapRoute
  DrugTestingRoute: typeof DrugTestingRoute
  DuiRoute: typeof DuiRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-impact': {
      id: '/community-impact'
      path: '/community-impact'
      fullPath: '/community-impact'
      preLoaderRoute: typeof CommunityImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counseling': {
      id: '/counseling'
      path: '/counseling'
      fullPath: '/counseling'
      preLoaderRoute: typeof CounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dot-sap': {
      id: '/dot-sap'
      path: '/dot-sap'
      fullPath: '/dot-sap'
      preLoaderRoute: typeof DotSapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drug-testing': {
      id: '/drug-testing'
      path: '/drug-testing'
      fullPath: '/drug-testing'
      preLoaderRoute: typeof DrugTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dui': {
      id: '/dui'
      path: '/dui'
      fullPath: '/dui'
      preLoaderRoute: typeof DuiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  ClassesRoute: ClassesRoute,
  CommunityImpactRoute: CommunityImpactRoute,
  ContactRoute: ContactRoute,
  CounselingRoute: CounselingRoute,
  DotSapRoute: DotSapRoute,
  DrugTestingRoute: DrugTestingRoute,
  DuiRoute: DuiRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
